import React, { useEffect } from 'react';

const STORAGE_KEY = 'mahar-pos-language-v2';
const MYANMAR = {
  Dashboard: 'ဒက်ရှ်ဘုတ်',
  'Sale POS': 'အရောင်း POS',
  'Sales History': 'အရောင်းမှတ်တမ်း',
  'Repair Platform': 'ဖုန်းပြင်စနစ်',
  'Advanced Repair Platform': 'အဆင့်မြင့်ဖုန်းပြင်စနစ်',
  'Partner & Settlement': 'မိတ်ဖက်နှင့် စာရင်းရှင်း',
  Products: 'ကုန်ပစ္စည်းများ',
  Stock: 'စတော့',
  Purchases: 'အဝယ်စာရင်း',
  'Customers & Credit': 'ဖောက်သည်နှင့် အကြွေး',
  'Finance & Accounts': 'ငွေစာရင်း',
  'Reports & Performance': 'အစီရင်ခံစာ',
  'Audit Trail': 'လုပ်ဆောင်မှုမှတ်တမ်း',
  'Backup & Recovery': 'Backup နှင့် Recovery',
  'Project Settings': 'Project Settings',
  'Money Service': 'ငွေလွှဲဝန်ဆောင်မှု',
  'Online Shop': 'အွန်လိုင်းဆိုင်',
  'ONLINE STORE': 'အွန်လိုင်းဆိုင်',
  'E-commerce Website': 'အွန်လိုင်းအရောင်းဆိုင်',
  'Store Setup': 'ဆိုင်ပြင်ဆင်မှု',
  'Products & Images': 'ပစ္စည်းနှင့်ပုံများ',
  'Orders': 'အော်ဒါများ',
  'Store': 'ဆိုင်',
  'Online Listed Products': 'အွန်လိုင်းတင်ထားသောပစ္စည်း',
  'New Orders': 'အော်ဒါအသစ်',
  'View Store': 'ဆိုင်ကြည့်ရန်',
  'Online Products': 'အွန်လိုင်းပစ္စည်းများ',
  'Offline Products': 'အွန်လိုင်းမတင်ရသေးသောပစ္စည်းများ',
  'All Brands': 'Brand အားလုံး',
  'All Categories': 'အမျိုးအစားအားလုံး',
  'All Stock Levels': 'လက်ကျန်အခြေအနေအားလုံး',
  'In Stock': 'လက်ကျန်ရှိ',
  'Low Stock': 'လက်ကျန်နည်း',
  'Out of Stock': 'ပစ္စည်းကုန်',
  'List': 'စာရင်း',
  'Grid': 'ကတ်ပုံစံ',
  'Select page': 'ယခုစာမျက်နှာရွေးရန်',
  'Publish Online': 'အွန်လိုင်းတင်မည်',
  'Take Offline': 'အွန်လိုင်းမှဖြုတ်မည်',
  'Published': 'အွန်လိုင်းတင်ပြီး',
  'Offline': 'အွန်လိုင်းမတင်ရသေး',
  'Previous': 'နောက်သို့',
  'Next': 'ရှေ့သို့',
  'Store Name': 'ဆိုင်အမည်',
  'Description': 'ဖော်ပြချက်',
  'Contact Phone': 'ဆိုင်ဖုန်း',
  'Telegram Chat Link': 'Telegram ဆက်သွယ်ရန်လင့်ခ်',
  'Shop Google Map Link': 'ဆိုင် Google Map လင့်ခ်',
  'Delivery Fee': 'ပို့ဆောင်ခ',
  'COD Delivery': 'အိမ်အရောက်ငွေချေ',
  'Shop Pickup': 'ဆိုင်တွင်လာယူ',
  'Save Store': 'ဆိုင်အချက်အလက်သိမ်းမည်',
  'Upload Photo': 'ပုံတင်မည်',
  'Save Details': 'အသေးစိတ်သိမ်းမည်',
  'Main Photo': 'အဓိကပုံ',
  'Set Main': 'အဓိကပုံထားမည်',
  'Delete': 'ဖျက်မည်',
  'Other Records': 'အခြားဝင်ငွေ နှင့်ထွက်ငွေ',
  'About Us': 'အကြောင်းအရာ',
  'Day Closed': 'နေ့ပိတ်ပြီး',
  'Daily Transfer / Cash Out Ledger': 'နေ့စဉ် ငွေလွှဲ / ငွေထုတ် စာရင်း',
  'Menu': 'မီနူး',
  Logout: 'ထွက်မည်',
  Refresh: 'ပြန်ဖတ်မည်',
  Save: 'သိမ်းမည်',
  Search: 'ရှာမည်',
  Print: 'ပရင့်ထုတ်မည်',
  'My Preference': 'ကျွန်ုပ်၏ Preference',
  'My Own Preference': 'ကျွန်ုပ်၏ Preference',
  'Slip Information': 'Slip အချက်အလက်',
  'Business Profile': 'ဆိုင်အချက်အလက်',
  'Appearance & Language': 'အပြင်အဆင်နှင့် ဘာသာစကား',
  'API Configure': 'API ချိတ်ဆက်မှု',
  'Users & Access': 'User နှင့် အသုံးပြုခွင့်',
  'PostgreSQL Settings': 'System Settings',
  'Save My Preference': 'Preference သိမ်းမည်',
  'Save Slip Information': 'Slip အချက်အလက် သိမ်းမည်',
  'Save Business Profile': 'ဆိုင်အချက်အလက် သိမ်းမည်',
  'Save Appearance': 'အပြင်အဆင် သိမ်းမည်',
  Language: 'ဘာသာစကား',
  Theme: 'အပြင်အဆင်',
  'Default Language': 'ပုံသေ ဘာသာစကား',
  'Default Theme': 'ပုံသေ အပြင်အဆင်',
  'Default Opening Page': 'စဖွင့်မည့် စာမျက်နှာ',
  Sidebar: 'ဘေးဘား',
  'Table Density': 'ဇယားအကွာအဝေး',
  'Page Size': 'စာမျက်နှာအရေအတွက်',
  'Date Format': 'ရက်စွဲပုံစံ',
  'Time Format': 'အချိန်ပုံစံ',
  Light: 'အလင်း',
  Dark: 'အမှောင်',
  System: 'စက်၏ပုံစံ',
  English: 'အင်္ဂလိပ်',
  'Business Name': 'လုပ်ငန်းအမည်',
  Subtitle: 'စာတန်းခွဲ',
  'Primary Phone': 'အဓိကဖုန်း',
  'Secondary Phone': 'ဒုတိယဖုန်း',
  Address: 'လိပ်စာ',
  'Township / Region': 'မြို့နယ် / ဒေသ',
  Website: 'Website',
  'Google Map URL': 'Google Map လင့်ခ်',
  'KBZ Pay Number': 'KBZ Pay နံပါတ်',
  'Wave Pay Number': 'Wave Pay နံပါတ်',
  'License Status': 'License အခြေအနေ',
  'Repair Voucher Print': 'Repair Voucher ထုတ်မည်',
  'New Repair': 'Repair အသစ်',
  'Access Denied': 'အသုံးပြုခွင့် မရှိပါ',
  'Back to Dashboard': 'Dashboard သို့ ပြန်မည်',
  'Search product, variant, SKU or barcode': 'Search product, variant, SKU or barcode',
  'Pick a product → review quantity and price in cart → confirm payment in 3 steps. The next action is shown below for beginner staff.': 'Product ရွေး → Cart ထဲမှာ Qty/Price စစ် → Payment Confirm လုပ်တဲ့ 3-step flow ပါ။ Beginner staff တွေအတွက် next action ကို အောက်မှာပြထားပါတယ်။',
  'Tap any product row to add it directly into the cart with POS sound.': 'Product row တစ်ခုကို နှိပ်တာနဲ့ Cart ထဲ တန်းထည့်ပြီး POS အသံပေးပါမယ်။',
  'Pick Product': 'Product ရွေးရန်',
  'Review Cart': 'Cart စစ်ရန်',
  'Save Payment': 'Payment သိမ်းရန်',
  'Add a product that has stock first.': 'Stock ရှိသော Product ကိုအရင်ထည့်ပါ။',
  'Tap any product row once.': 'Product row ကိုတစ်ချက်နှိပ်ပါ။',
  'Customer name or phone is required for credit sale.': 'Credit sale အတွက် Customer Name သို့ Phone လိုအပ်ပါသည်။',
  'Split Payment Setup': 'ငွေပေးချေမှု ခွဲထည့်ရန်',
  'Add another payment row': '+ Payment Row ထပ်ထည့်မယ်',
  'Use single payment again': 'Single Payment ပြန်သုံးမယ်',
  'Edit split payment': 'Split Payment ပြင်မယ်',
  'Invoice, Customer, Payment, Status နဲ့ Cashier အလိုက် ရှာဖွေပြီး Detail, Reprint, Export နဲ့ Void ကို စီမံပါ။': 'Invoice, Customer, Payment, Status နဲ့ Cashier အလိုက် ရှာဖွေပြီး Detail, Reprint, Export နဲ့ Void ကို စီမံပါ။',
  'Filter ကိုပြောင်းပြီး ပြန်ရှာပါ။': 'Filter ကိုပြောင်းပြီး ပြန်ရှာပါ။',
  'Customer profile၊ credit balance၊ payment collection နဲ့ sale history ကို workflow တစ်ခုတည်းအဖြစ် ချိတ်ဆက်စီမံပါ။': 'Customer profile၊ credit balance၊ payment collection နဲ့ sale history ကို workflow တစ်ခုတည်းအဖြစ် ချိတ်ဆက်စီမံပါ။',
  'Customer name ထည့်ပါ။': 'Customer name ထည့်ပါ။',
  'Please choose a wallet account.': 'Wallet account ရွေးရန်လိုပါတယ်',
  'No cash account is configured yet.': 'Cash account မရှိသေးပါ',
  'We will receive the customer wallet amount and pay out cash.': 'Customer wallet ဝင်ငွေကိုယူပြီး Cash ထုတ်ပေးပါမယ်။',
  'Money will leave your wallet and cash will come in from the customer.': 'ကိုယ့် Wallet ထဲကငွေထွက်ပြီး Customer ဆီက Cash ဝင်ပါမယ်။',
  'The customer will transfer into this wallet.': 'Customer က ဒီ Wallet ထဲကို လွှဲပေးပါမယ်။',
  'Money will transfer out from this wallet.': 'ဒီ Wallet ထဲကနေ ငွေလွှဲထွက်ပါမယ်။',
  'Because this is cash out, the cash account will be paid out automatically.': 'Cash Out ဖြစ်လို့ Cash account ကနေ အလိုအလျောက်ထုတ်ပေးပါမယ်။',
  'Because this is transfer, cash will come in from the customer.': 'Transfer ဖြစ်လို့ Customer ဆီက Cash ဝင်ပါမယ်။',
  'Record transfer and cash out from one place.': 'Transfer နဲ့ Cash Out ကို တစ်နေရာတည်းကနေ စာရင်းသွင်းပါ။',
  'Sales၊ profit၊ payments၊ customer credit၊ repair နဲ့ inventory health ကို ဆက်စပ်ပြီး ဆုံးဖြတ်ချက်ချနိုင်အောင် တစ်နေရာထဲကြည့်ပါ။': 'Sales၊ profit၊ payments၊ customer credit၊ repair နဲ့ inventory health ကို ဆက်စပ်ပြီး ဆုံးဖြတ်ချက်ချနိုင်အောင် တစ်နေရာထဲကြည့်ပါ။',
  'Product မတွေ့ပါ': 'Product မတွေ့ပါ',
  'Search/filter ပြောင်းပါ သို့ Product အသစ်ထည့်ပါ။': 'Search/filter ပြောင်းပါ သို့ Product အသစ်ထည့်ပါ။',
  'Variant မရှိသေးပါ': 'Variant မရှိသေးပါ',
  'Product information ကို PostgreSQL tenant database ထဲ သိမ်းပါမယ်။': 'Product information ကို PostgreSQL tenant database ထဲ သိမ်းပါမယ်။',
  'IMEI / Serial လိုအပ် (Phone stock အတွက်)': 'IMEI / Serial လိုအပ် (Phone stock အတွက်)',
  'Step 1': 'Step 1',
  'Product Name ထည့်ပြီး Save Product နှိပ်ပါ။ ပြီးရင် Add Variant ဆက်လုပ်ပါ။': 'Product Name ထည့်ပြီး Save Product နှိပ်ပါ။ ပြီးရင် Add Variant ဆက်လုပ်ပါ။',
  'ဥပမာ: COKE-350ML': 'ဥပမာ: COKE-350ML',
  'ဥပမာ: RN15P-8-256': 'ဥပမာ: RN15P-8-256',
  'ဝယ်ဈေး': 'ဝယ်ဈေး',
  'ရောင်းဈေး': 'ရောင်းဈေး',
  'အနိမ့်ဆုံးဈေး': 'အနိမ့်ဆုံးဈေး',
  'Add, edit, or deactivate product categories.': 'Product Categories ကို Add၊ Edit၊ Deactivate လုပ်ပါ။',
  'ဆိုင်အကောင့်ဖြင့် Login ဝင်ပြီး Products API ကို ချိတ်ပါ။': 'ဆိုင်အကောင့်ဖြင့် Login ဝင်ပြီး Products API ကို ချိတ်ပါ။',
  'Manage products, categories, barcodes, units, expiry, prices, and stock in one place.': 'ပစ္စည်း၊ အမျိုးအစား၊ ဘားကုဒ်၊ ယူနစ်၊ သက်တမ်း၊ ဈေးနှုန်းနှင့် စတော့ကို တစ်နေရာတည်းတွင် စီမံပါ။',
  'ပစ္စည်းနာမည်၊ SKU သို့ Barcode ရှာရန်...': 'ပစ္စည်းနာမည်၊ SKU သို့ Barcode ရှာရန်...',
  'ဥပမာ: Coca Cola 350ml, ဆန် ၂၄ပြည်, ဆီ ၁လီတာ': 'ဥပမာ: Coca Cola 350ml, ဆန် ၂၄ပြည်, ဆီ ၁လီတာ',
  'ဥပမာ: Coca Cola 350ml': 'ဥပမာ: Coca Cola 350ml',
  'ဥပမာ: Drinks, Food, Household, Medicine': 'ဥပမာ: Drinks, Food, Household, Medicine',
  'Package/Size ကိုရေးပါ။ ဥပမာ: 350ml / 1kg / 12pcs box / Single': 'Package/Size ကိုရေးပါ။ ဥပမာ: 350ml / 1kg / 12pcs box / Single',
  'ဥပမာ: 350ml': 'ဥပမာ: 350ml',
  'ဆိုင်တွင်း product code ရှိရင်ထည့်ပါ။ မရှိရင် blank ထားလို့ရပါတယ်။': 'ဆိုင်တွင်း product code ရှိရင်ထည့်ပါ။ မရှိရင် blank ထားလို့ရပါတယ်။',
  'Barcode scanner သုံးမယ်ဆို Barcode နံပါတ်ထည့်ပါ။': 'Barcode scanner သုံးမယ်ဆို Barcode နံပါတ်ထည့်ပါ။',
  'ရေတွက်မယ့် unit ထည့်ပါ။ ဥပမာ: pcs / bottle / pack / box / kg': 'ရေတွက်မယ့် unit ထည့်ပါ။ ဥပမာ: pcs / bottle / pack / box / kg',
  'စားသောက်ကုန်/ဆေးဝါးလို သက်တမ်းကုန်ရက်ရှိတဲ့ပစ္စည်းဆို ထည့်ပါ။ မရှိရင် blank ထားပါ။': 'စားသောက်ကုန်/ဆေးဝါးလို သက်တမ်းကုန်ရက်ရှိတဲ့ပစ္စည်းဆို ထည့်ပါ။ မရှိရင် blank ထားပါ။',
  'တစ်ခုဝယ်ဈေး / cost ထည့်ပါ။ Profit report အတွက်သုံးပါမယ်။': 'တစ်ခုဝယ်ဈေး / cost ထည့်ပါ။ Profit report အတွက်သုံးပါမယ်။',
  'Customer ကိုရောင်းမယ့် ပုံမှန်ဈေး။': 'Customer ကိုရောင်းမယ့် ပုံမှန်ဈေး။',
  'လက်ကားဈေးရှိမှထည့်ပါ။ မရှိရင် 0 ထားပါ။': 'လက်ကားဈေးရှိမှထည့်ပါ။ မရှိရင် 0 ထားပါ။',
  'Discount ပေးလို့ရမယ့် အနိမ့်ဆုံးရောင်းဈေး။ မသုံးရင် Selling Price နဲ့တူထားပါ။': 'Discount ပေးလို့ရမယ့် အနိမ့်ဆုံးရောင်းဈေး။ မသုံးရင် Selling Price နဲ့တူထားပါ။',
  'လက်ရှိဆိုင်မှာရှိနေတဲ့ အရေအတွက်ကိုထည့်ပါ။': 'လက်ရှိဆိုင်မှာရှိနေတဲ့ အရေအတွက်ကိုထည့်ပါ။',
  'ဒီအရေအတွက်အောက်ရောက်ရင် Low Stock warning ပြပါမယ်။': 'ဒီအရေအတွက်အောက်ရောက်ရင် Low Stock warning ပြပါမယ်။',
  'ဖုန်း၊ Accessories၊ Category၊ Brand/Model၊ Specs၊ Price နဲ့ Stock ကို တစ်နေရာတည်းမှာ စီမံပါ။': 'ဖုန်း၊ Accessories၊ Category၊ Brand/Model၊ Specs၊ Price နဲ့ Stock ကို တစ်နေရာတည်းမှာ စီမံပါ။',
  'ဖုန်း/ပစ္စည်းနာမည်၊ SKU၊ IMEI သို့ Barcode ရှာရန်...': 'ဖုန်း/ပစ္စည်းနာမည်၊ SKU၊ IMEI သို့ Barcode ရှာရန်...',
  'ဥပမာ: Redmi Note 15 Pro, iPhone 13, Type-C Charger': 'ဥပမာ: Redmi Note 15 Pro, iPhone 13, Type-C Charger',
  'ဥပမာ: Redmi Note 15 Pro': 'ဥပမာ: Redmi Note 15 Pro',
  'ဥပမာ: Phones, Cases, Charger, Power Bank': 'ဥပမာ: Phones, Cases, Charger, Power Bank',
  'Brand ထည့်ပါ။ ဥပမာ: Redmi / Vivo / iPhone / Samsung': 'Brand ထည့်ပါ။ ဥပမာ: Redmi / Vivo / iPhone / Samsung',
  'Model ထည့်ပါ။ ဥပမာ: Note 15 Pro / Y28 / 13 Pro Max': 'Model ထည့်ပါ။ ဥပမာ: Note 15 Pro / Y28 / 13 Pro Max',
  'Customer မြင်မယ့် specs ကိုရေးပါ။ ဥပမာ: 8GB / 256GB / Black': 'Customer မြင်မယ့် specs ကိုရေးပါ။ ဥပမာ: 8GB / 256GB / Black',
  'ဥပမာ: 8GB / 256GB / Black': 'ဥပမာ: 8GB / 256GB / Black',
  'ဆိုင်တွင်း product code ရှိရင်ထည့်ပါ။ ဥပမာ: RN15P-8-256': 'ဆိုင်တွင်း product code ရှိရင်ထည့်ပါ။ ဥပမာ: RN15P-8-256',
  'Accessories barcode ရှိရင်ထည့်ပါ။ Phone IMEI က sale ချိန်မှာထည့်လို့ရပါတယ်။': 'Accessories barcode ရှိရင်ထည့်ပါ။ Phone IMEI က sale ချိန်မှာထည့်လို့ရပါတယ်။',
  'အများအားဖြင့် pcs ထားပါ။ Accessories pack/box ဆို pack/box ထည့်နိုင်ပါတယ်။': 'အများအားဖြင့် pcs ထားပါ။ Accessories pack/box ဆို pack/box ထည့်နိုင်ပါတယ်။',
  'Phone/Accessories အတွက် မလိုရင် blank ထားပါ။': 'Phone/Accessories အတွက် မလိုရင် blank ထားပါ။',
  'Phone RAM ထည့်ပါ။ ဥပမာ: 8GB': 'Phone RAM ထည့်ပါ။ ဥပမာ: 8GB',
  'Phone Storage ထည့်ပါ။ ဥပမာ: 128GB / 256GB': 'Phone Storage ထည့်ပါ။ ဥပမာ: 128GB / 256GB',
  'အရောင်ထည့်ပါ။ ဥပမာ: Black / Blue / Gold': 'အရောင်ထည့်ပါ။ ဥပမာ: Black / Blue / Gold',
  'တစ်လုံး/တစ်ခု ဝယ်ဈေး။ Profit တွက်ဖို့လိုပါတယ်။': 'တစ်လုံး/တစ်ခု ဝယ်ဈေး။ Profit တွက်ဖို့လိုပါတယ်။',
  'လက်ကား/Dealer price ရှိမှထည့်ပါ။ မရှိရင် 0 ထားပါ။': 'လက်ကား/Dealer price ရှိမှထည့်ပါ။ မရှိရင် 0 ထားပါ။',
  'အနိမ့်ဆုံးရောင်းနိုင်တဲ့ဈေး။ Discount approval အတွက်သုံးပါမယ်။': 'အနိမ့်ဆုံးရောင်းနိုင်တဲ့ဈေး။ Discount approval အတွက်သုံးပါမယ်။',
  'လက်ရှိ stock အရေအတွက်ထည့်ပါ။ Phone serial များရင် qty ထည့်ပြီး sale ချိန် IMEI ထည့်ပါ။': 'လက်ရှိ stock အရေအတွက်ထည့်ပါ။ Phone serial များရင် qty ထည့်ပြီး sale ချိန် IMEI ထည့်ပါ။',
  'Record new incoming stock.': 'ပစ္စည်းအသစ် ဝင်စာရင်းသွင်းမည်',
  'Record manual outgoing stock.': 'လက်ဖြင့် ပစ္စည်းထုတ်စာရင်းသွင်းမည်',
  'Adjust stock balance up or down.': 'လက်ကျန်ကို အတိုး/အလျော့ ပြင်ဆင်မည်',
  'Reduce as damaged stock.': 'ပျက်စီးပစ္စည်းအဖြစ် လျှော့မည်',
  'Reduce as repair usage stock.': 'ပြင်ဆင်ရေးသုံးပစ္စည်းအဖြစ် လျှော့မည်',
  'Please enter a note.': 'မှတ်ချက်ထည့်ပေးပါ။',
  'Example — cracked screen, water damage': 'ဥပမာ — မျက်နှာပြင်ကွဲ၊ ရေစို',
  'Example — used for Repair ID MS0551': 'ဥပမာ — Repair ID MS0551 အတွက်သုံး',
  'Reason / note': 'အကြောင်းပြချက် / မှတ်ချက်',
  'Stock is not enough. If negative stock is disabled, the server will reject this.': 'လက်ကျန်မလုံလောက်ပါ။ Negative stock ပိတ်ထားပါက Server က ငြင်းပါမယ်။',
  'Manage Stock In, Stock Out, Adjustment, Damage, and Repair Usage for each product variant.': 'Product Variant တစ်ခုချင်းစီအတွက် Stock In, Stock Out, Adjustment, Damage နဲ့ Repair Usage ကို စီမံပါ။',
  'Add variants in Products first.': 'Products ထဲမှာ Variant အရင်ထည့်ပါ။',
};

Object.assign(MYANMAR, {
  'Browser popup blocked. Allow popups and try reprint again.': 'Browser popup blocked. Popups ကို Allow လုပ်ပြီး Reprint ပြန်နှိပ်ပါ။',
  'No sale history is available to export.': 'Export လုပ်ရန် Sale History မရှိပါ။',
  'Search by invoice, customer, payment, status, or cashier, then manage detail, reprint, export, and void from one place.': 'Invoice, Customer, Payment, Status နဲ့ Cashier အလိုက် ရှာဖွေပြီး Detail, Reprint, Export နဲ့ Void ကို စီမံပါ။',
  'Change the filters and search again.': 'Filter ကိုပြောင်းပြီး ပြန်ရှာပါ။',
  'Save a product first, then add a variant.': 'Product အရင် Save လုပ်ပါ။ ပြီးမှ Variant ထည့်ပါ။',
  'Please enter a product name.': 'Product name ထည့်ပါ',
  'Product saved. Continue with variant or stock setup.': 'Product သိမ်းပြီးပါပြီ။ Variant / Stock ဆက်ထည့်ပါ။',
  'New product saved. Add variants from Add Variant.': 'Product အသစ် သိမ်းပြီးပါပြီ။ Variant ကို Add Variant မှာသီးသန့်ထည့်ပါ',
  'Product updated successfully.': 'Product ပြင်ဆင်ပြီးပါပြီ',
  'Product deactivated successfully.': 'Product ကို Deactivate လုပ်ပြီးပါပြီ',
  'Please enter a display name.': 'Display name ထည့်ပါ',
  'New variant added successfully.': 'Variant အသစ် ထည့်ပြီးပါပြီ',
  'Variant and specs updated successfully.': 'Variant / specs ပြင်ဆင်ပြီးပါပြီ',
  'Variant deactivated successfully.': 'Variant ကို Deactivate လုပ်ပြီးပါပြီ',
  'Category updated successfully.': 'Category ပြင်ပြီးပါပြီ',
  'New category added successfully.': 'Category အသစ် ထည့်ပြီးပါပြီ',
  'Category deactivated successfully.': 'Category ကို Deactivate လုပ်ပြီးပါပြီ',
  'No products found': 'Product မတွေ့ပါ',
  'Change search or filters, or add a new product.': 'Search/filter ပြောင်းပါ သို့ Product အသစ်ထည့်ပါ။',
  'No variants yet': 'Variant မရှိသေးပါ',
  'Product information will be saved in the PostgreSQL tenant database.': 'Product information ကို PostgreSQL tenant database ထဲ သိမ်းပါမယ်။',
  'IMEI / Serial required for phone stock': 'IMEI / Serial လိုအပ် (Phone stock အတွက်)',
  'Step 1: Enter the product name and save the product, then continue to Add Variant.': 'Step 1 Product Name ထည့်ပြီး Save Product နှိပ်ပါ။ ပြီးရင် Add Variant ဆက်လုပ်ပါ။',
  'Step 2: Enter selling price, minimum price, and opening stock, then save the variant and continue to Sale POS.': 'Step 2 Selling Price / Minimum Price / Opening Stock ထည့်ပြီး Save Variant နှိပ်ပါ။ ပြီးရင် Sale POS သွားရောင်းပါ။',
  'Please enter a customer name.': 'Customer name ထည့်ပါ။',
  'Manage customer profiles, credit balances, payment collection, and sales history in one connected workflow.': 'Customer profile၊ credit balance၊ payment collection နဲ့ sale history ကို workflow တစ်ခုတည်းအဖြစ် ချိတ်ဆက်စီမံပါ။',
  'View sales, profit, payments, customer credit, repairs, and inventory health together for faster decisions.': 'Sales၊ profit၊ payments၊ customer credit၊ repair နဲ့ inventory health ကို ဆက်စပ်ပြီး ဆုံးဖြတ်ချက်ချနိုင်အောင် တစ်နေရာထဲကြည့်ပါ။',
  'Manage shop info, slip setup, users, theme, and system setup in one simple place.': 'ဆိုင်အချက်အလက်၊ slip၊ user၊ theme နဲ့ system setup များကို ရိုးရှင်းစွာ စီမံပါ။',
  'These preferences apply only to the current logged-in user.': 'ဒီ Login User တစ်ယောက်အတွက်ပဲ သက်ရောက်မည့် Preference များ။',
  'Show Money Service menu': 'Money Service Menu ပြမည်',
  'This is hidden by default. Enable it only to use cash in or cash out.': 'ဤလုပ်ဆောင်ချက်ကို ပုံမှန်အားဖြင့် ဖျောက်ထားသည်။ ငွေသွင်း သို့မဟုတ် ငွေထုတ် အသုံးပြုလိုမှ ဖွင့်ပါ။',
  'Sale slip logo, header, footer, and footer tag information.': 'Sale Slip အတွက် Logo, Header, Footer နှင့် Footer Tag Information။',
  'Sale slip and repair voucher logo and footer tag information.': 'Sale Slip နဲ့ Repair Voucher အတွက် Logo နှင့် Footer Tag Information။',
  'Manage shop name, phone numbers, address, and logo here.': 'ဆိုင်အမည်၊ ဖုန်းနံပါတ်၊ လိပ်စာနှင့် logo ကို စီမံပါ။',
  'Manage default page size, session timeout, and timezone.': 'Default page size၊ session timeout နှင့် timezone ကို စီမံပါ။',
  'Business setup modules': 'လုပ်ငန်း setup များ',
  'Shop info, user, and slip setup': 'ဆိုင်အချက်အလက်၊ user၊ slip',
  'Track exactly who did what, when, and from where with a tamper-evident hash chain.': 'ဘယ်သူ၊ ဘယ်အချိန်၊ ဘယ်နေရာကနေ၊ ဘာလုပ်ခဲ့သလဲကို tamper-evident hash chain နဲ့ တိတိကျကျမှတ်တမ်းတင်ထားပါတယ်။',
  'Monitor PostgreSQL backup freshness, SHA-256 integrity, and retention policy from here.': 'PostgreSQL backup freshness၊ SHA-256 integrity နဲ့ retention policy ကို ဒီနေရာက စောင့်ကြည့်နိုင်ပါတယ်။',
  'Select a user, then open only the section you want to edit.': 'User ရွေးပြီး လိုအပ်တဲ့ section ကိုနှိပ်မှ Form ပေါ်ပါမယ်။',
  'Set a new temporary password.': 'Temporary password အသစ်သတ်မှတ်ရန်',
  'Show or hide menu tabs for this user.': 'User မြင်ရမည့် Menu Tabs ကို Show / Hide လုပ်ရန်',
  'Permanently remove this staff or cashier account.': 'Staff / Cashier account ကိုအပြီးဖယ်ရှားရန်',
  'Allow or block each function one by one.': 'လုပ်ဆောင်ချက်တစ်ခုချင်းစီကို Allow / Block လုပ်ရန်',
  'Apps Script code and Script Properties can be copied, then you only need to paste one Web App URL to connect.': 'Apps Script code နဲ့ Script Properties ကို copy လုပ်ပြီး Web App URL တစ်ခုတည်း paste လုပ်ရုံနဲ့ ချိတ်နိုင်ပါတယ်။',
  'Quick setup steps': 'သုံးနည်းအကျဉ်း',
  'Open Google Sheet → Extensions → Apps Script.': 'Google Sheet ဖွင့် → Extensions → Apps Script ကိုဝင်ပါ။',
  'Copy the Apps Script code below and paste it there.': 'အောက်က Apps Script Code ကို Copy လုပ်ပြီး paste ပါ။',
  'In Script Properties, add POS_BASE_URL, POS_SHOP_SLUG, and POS_SYNC_SECRET from Copy Properties.': 'Script Properties ထဲမှာ POS_BASE_URL, POS_SHOP_SLUG, POS_SYNC_SECRET ကို Copy Properties နဲ့ထည့်ပါ။',
  'Deploy → New deployment → Web app → deploy with Anyone with the link.': 'Deploy → New deployment → Web app → Anyone with the link ဖြင့် deploy ပါ။',
  'Paste the generated Web App URL into Web App URL → Enable → Save → click Test POST/GET.': 'ရလာတဲ့ Web App URL ကို Web App URL ထဲ paste → Enable → Save → Test POST/GET နှိပ်ပါ။',
  'Paste into Script Properties': 'Script Properties ထဲထည့်ရန်',
  'Paste this secret into Script Properties as POS_SYNC_SECRET. No manual generate is needed.': 'ဒီ secret ကို Script Properties ထဲက POS_SYNC_SECRET အနေနဲ့ paste လုပ်ပါ။ Manual generate မလိုပါဘူး။',
  'Prices & Discounts': 'ဈေးနှုန်းနှင့် လျော့ဈေးများ',
  'Retail Menu Guide': 'အရောင်းဆိုင် မီနူးလမ်းညွှန်',
  'Menu / Sidebar Guide': 'Menu / Sidebar လမ်းညွှန်',
  'Use the sidebar to open POS, Sales History, Products, Stock, Purchases, Reports, and Settings. Repair and Partner Settlement are hidden for retail shops. Money Service appears after it is enabled in Settings. On mobile, tap Menu at the top left.': 'ဘေးဘားမှ အရောင်း POS၊ အရောင်းမှတ်တမ်း၊ ပစ္စည်းများ၊ စတော့၊ အဝယ်စာရင်း၊ အစီရင်ခံစာနှင့် ဆက်တင်များကို ဖွင့်နိုင်သည်။ အရောင်းဆိုင်အမျိုးအစားတွင် ဖုန်းပြင်နှင့် မိတ်ဖက်စာရင်းရှင်းကို ဖျောက်ထားသည်။ ငွေလွှဲဝန်ဆောင်မှုကို ဆက်တင်တွင် ဖွင့်ပြီးမှ ပေါ်မည်။ မိုဘိုင်းတွင် အပေါ်ဘယ်ဘက်ရှိ မီနူးကိုနှိပ်ပါ။',
  'From the left sidebar you can open Sale POS, Products, Stock, Money Service, Reports, and Settings. On mobile, tap the top-left Menu button to open the sidebar.': 'ဘယ်ဘက် Sidebar ထဲကနေ Sale POS, Products, Stock, Money Service, Reports နဲ့ Settings တွေကိုဝင်သုံးနိုင်ပါတယ်။ Mobile မှာဆိုရင် အပေါ်ဘယ်ဘက် Menu ခလုတ်ကိုနှိပ်ပြီး Sidebar ကိုဖွင့်ပါ။',
  'Open Menu': 'Menu ဖွင့်ကြည့်မယ်',
  'Got it': 'နားလည်ပါပြီ',
  'Set up product, variant, and stock before you start selling.': 'အရင်ဆုံး Product / Variant / Stock ထည့်ပြီးမှ ရောင်းပါ',
  'For a phone shop, set up product, variant, price, stock, and whether IMEI is required first on the Products page.': 'Phone Shop အတွက် Products page မှာ Product, Variant, Price, Stock နဲ့ IMEI လို/မလို အရင်သတ်မှတ်ပါ။',
  'Open Products page': 'Products page ဖွင့်မယ်',
  'Add product → variant → price → stock step by step.': 'Product → Variant → Price → Stock အဆင့်ဆင့်ထည့်ပါ',
  'Click Add Product and save the product. Then in Add Variant, enter selling price, minimum price, and opening stock.': 'Add Product ကိုနှိပ်ပြီး Product သိမ်းပါ။ ပြီးရင် Add Variant မှာ Selling Price, Minimum Price, Opening Stock ထည့်ပါ။',
  'Open Add Product form': 'Add Product form ဖွင့်မယ်',
  'Add variant / stock': 'Add Variant / Stock ထည့်မယ်',
  'Go to Sale POS': 'Sale POS သွားမယ်',
  'Check stock from each product variant.': 'Stock ကို Product Variant မှတစ်ဆင့်စစ်ပါ',
  'Enter opening stock inside the variant, then sell from Sale POS.': 'Opening Stock ကို Variant ထဲမှာထည့်ပြီး Sale POS မှာ ရောင်းချပါ။',
  'Set up product, unit, expiry, and stock first.': 'ပစ္စည်း၊ ယူနစ်၊ သက်တမ်းနှင့် စတော့ကို အရင်သတ်မှတ်ပါ။',
  'Before selling, set the barcode, unit, expiry date, price, and opening stock on the Products page.': 'မရောင်းမီ ပစ္စည်းစာမျက်နှာတွင် ဘားကုဒ်၊ ယူနစ်၊ သက်တမ်းကုန်ရက်၊ ဈေးနှုန်းနှင့် အဖွင့်စတော့ကို သတ်မှတ်ပါ။',
  'Add product → unit → expiry → opening stock.': 'Product → Unit → Expiry → Opening Stock ထည့်ပါ',
  'After Add Product, open Add Variant and enter barcode, unit, expiry date, selling price, and opening stock. Then continue to Sale POS.': 'Add Product ပြီးရင် Add Variant မှာ Barcode, Unit, Expiry Date, Selling Price, Opening Stock ထည့်ပါ။ ပြီးမှ Sale POS မှာရောင်းပါ။',
  'Add variant / unit / expiry': 'Variant / Unit / Expiry ထည့်မယ်',
  'Sell in Sale POS': 'Sale POS မှာရောင်းမယ်',
  'Check stock and expiry from each variant.': 'Stock / Expiry ကို Variant မှတစ်ဆင့်စစ်ပါ',
  'Enter opening stock, low stock alert, and expiry date inside the variant, then sell from Sale POS.': 'Opening Stock, Low Stock Alert, Expiry Date ကို Variant ထဲမှာထည့်ပြီး Sale POS မှာရောင်းပါ။',
  'Hide from future selection? History will stay safe.': 'ကို future selection မှာ မပြတော့ဘူးလား? History မပျက်ပါ။',
  'Only active items can be selected in forms.': 'Forms မှာ ဒီ active list ကိုသာရွေးနိုင်မယ်',
  'Configure in Project Settings': 'Project Settings မှာစီမံပါ',
  'POS Payment Types are managed here. Cash In / Out wallets stay in the Fees tab.': 'POS Payment Types are managed here. Cash In / Out wallets stay in the Fees tab.',
  'POS Payment Type Configure': 'POS Payment Type Configure',
  'Manage the Cash / KBZ Pay / Wave Pay / Bank payment methods shown in Sale POS checkout here.': 'Sale POS checkout မှာပေါ်မယ့် Cash / KBZ Pay / Wave Pay / Bank payment methods တွေကို ဒီနေရာမှာပဲစီမံပါ.',
  'Choose which payment types appear in Sale POS Payment.': 'Sale POS Payment မှာပေါ်မယ့် payment type ကိုရွေးတာပါ',
  'This area only controls whether a payment option appears in POS checkout. Manage Cash In / Cash Out wallet balance links separately in Fees → Wallet Link.': 'ဒီနေရာက POS Sale checkout မှာ payment option ပေါ်/မပေါ်ကိုပဲပြောင်းမယ်။ Cash In / Cash Out wallet balance link ကို Fees → Wallet Link မှာ သီးသန့်စီမံပါ။',
  'Only the payment types shown here will appear in Sale POS Payment. Cash In / Out links are not affected.': 'ပြထားသော payment type များသာ Sale POS Payment မှာပေါ်မယ်။ Cash In / Out link ကိုမထိပါ။',
  'Payment: hidden in POS': 'Payment: POS မှာမပြထား',
  'Payment: shown in POS': 'Payment: POS မှာပြထား',
  'Rename': 'နာမည်ပြင်',
  'Show in POS': 'POS ပြရန်',
  'Hide in POS': 'POS မပြရန်',
  'View list or open configure.': 'List ကြည့်ရန် သို့ Configure လုပ်ရန် နှိပ်ပါ',
  'Please choose a wallet account.': 'Wallet account ရွေးရန်လိုပါတယ်',
  'No cash account has been configured yet.': 'Cash account မရှိသေးပါ',
  'We will receive the customer wallet amount and pay out cash.': 'Customer wallet ဝင်ငွေကိုယူပြီး Cash ထုတ်ပေးပါမယ်။',
  'Money will leave your wallet and cash will come in from the customer.': 'ကိုယ့် Wallet ထဲကငွေထွက်ပြီး Customer ဆီက Cash ဝင်ပါမယ်။',
  'The customer will transfer into this wallet.': 'Customer က ဒီ Wallet ထဲကို လွှဲပေးပါမယ်။',
  'Money will transfer out from this wallet.': 'ဒီ Wallet ထဲကနေ ငွေလွှဲထွက်ပါမယ်။',
  'Because this is cash out, the cash account will be paid out automatically.': 'Cash Out ဖြစ်လို့ Cash account ကနေ အလိုအလျောက်ထုတ်ပေးပါမယ်။',
  'Because this is transfer, cash will come in from the customer.': 'Transfer ဖြစ်လို့ Customer ဆီက Cash ဝင်ပါမယ်။',
  'Record transfer and cash out from one place.': 'Transfer နဲ့ Cash Out ကို တစ်နေရာတည်းကနေ စာရင်းသွင်းပါ။',
  'Money Service Ledger': 'Money Service Ledger',
  'Configured wallets and service fees': 'Configured wallets and service fees',
  'Payment Type Configure': 'Payment Type Configure',
  'Manage the Cash, KBZ Pay, Wave Pay, and Bank/Wallet methods shown in POS Sale.': 'POS Sale မှာပေါ်မယ့် Cash, KBZ Pay, Wave Pay, Bank/Wallet တွေကို စီမံရန်.',
  'Fees': 'Fees',
  'Add a wallet if needed, then set Cash In % and Cash Out %.': 'Add a wallet if needed, then set Cash In % and Cash Out %.',
  'KPay / Wave Pay transfers, cash out, and service fees are recorded in PostgreSQL.': 'KPay / Wave Pay ငွေလွှဲ၊ ငွေထုတ်နှင့် service fee ကို PostgreSQL တွင်မှတ်တမ်းတင်ပါ။',
  'Set percentage values for each transaction type.': 'Transaction type တစ်ခုချင်းစီအတွက် percentage သတ်မှတ်ပါ။',
  'No stock left for sale.': 'ပစ္စည်းလက်ကျန် မရှိတော့ပါ။',
  'Added to cart.': '→ Cart ထည့်ပြီး',
  'Not enough stock to add more.': 'ထပ်ထည့်ရန် Stock မလုံလောက်ပါ။',
  'Clear all items from the cart?': 'Cart ထဲက ပစ္စည်းအားလုံးကို ရှင်းမလား?',
  'Cart cleared and stock released.': 'Cart ရှင်းပြီး Stock ပြန်လွှတ်ထားသည်။',
  'There are no items in the cart.': 'Cart ထဲတွင် ပစ္စည်းမရှိပါ။',
  'Choose a payment type from Project Settings.': 'Project Settings မှ Payment Type တစ်ခုရွေးပါ။',
  'Sale price is below the minimum price.': 'ရောင်းဈေးသည် Minimum Price အောက်ရောက်နေသည်။',
  'Enter IMEI / Serial.': 'IMEI / Serial ထည့်ပါ။',
  'Enter customer name or phone for credit sale.': 'Credit sale အတွက် Customer Name သို့ Phone ထည့်ပါ။',
  'Received cash is less than the total.': 'လက်ခံငွေသည် စုစုပေါင်းထက် နည်းနေသည်။',
  'Search product, SKU or barcode…': 'Product, SKU or Barcode ရှာပါ…',
  'All': 'အားလုံး',
  'No in-stock products found for sale.': 'ရောင်းရန် Stock ရှိသော ပစ္စည်းမတွေ့ပါ။',
  'Item': 'ပစ္စည်း',
  'Price': 'ဈေးနှုန်း',
  'Qty': 'အရေ',
  'Total Due': 'ကျသင့်',
  'Cart is still empty.': 'Cart ထဲ ပစ္စည်းမရှိသေး',
  'Items': 'ပစ္စည်းအရေ',
  'Base Price': 'မူရင်းဈေး',
  'Price Override': 'ဈေးပြင် (Override)',
  'Grand Total': 'စုစုပေါင်း',
  'Received / Change': 'လက်ခံငွေ / အမ်းငွေ',
  'Reload payment types from Project Settings': 'Project Settings Payment Types ပြန်ယူမည်',
  'Checkout': 'ငွေရှင်းမည်',
  'Weekly Settlement Center': 'အပတ်စဉ် စာရင်းရှင်းစင်တာ',
  'Add Partner Shop': 'Partner Shop ထည့်မည်',
  'Sync Completed': 'ပြီးစီးပြီးသားများကို Sync လုပ်မည်',
  'New Settlement': 'Settlement အသစ်',
  'Open settlements': 'ဖွင့်ထားသော settlement များ',
  'Draft / Confirmed / Partial': 'Draft / Confirmed / Partial',
  'PARTNER SHOP': 'PARTNER SHOP',
  'Supplier Payable': 'Supplier ပေးရန်ကျန်ငွေ',
  'Paid today': 'ယနေ့ပေးချေပြီး',
  'Suppliers & Purchase Orders': 'Supplier နှင့် Purchase Order များ',
  Suppliers: 'Supplier များ',
  'Purchase Orders': 'Purchase Order များ',
  'Receiving & Accounts': 'လက်ခံခြင်းနှင့် စာရင်း',
  'Direct Receiving': 'တိုက်ရိုက် လက်ခံခြင်း',
  'Manage suppliers, orders, receiving, payables, returns, repair parts and reports.': 'Supplier, order, receiving, payable, return, repair parts နှင့် report များကို စီမံပါ။',
  'Purchasing sections': 'Purchasing section များ',
  'Shop Admin Only': 'Shop Admin သာ အသုံးပြုနိုင်သည်',
  'Branch & Staff Management': 'Branch နှင့် Staff စီမံခန့်ခွဲမှု',
  Branches: 'Branch များ',
  Staff: 'Staff',
  'Shop users': 'ဆိုင်အသုံးပြုသူများ',
  'Stock Units': 'Stock ယူနစ်',
  'All branches': 'Branch အားလုံး',
  'Edit Branch': 'Branch ပြင်မည်',
  'Create Branch': 'Branch ဖန်တီးမည်',
  'Branch data is scoped under this shop only': 'ဒီ shop အောက်က branch data ကိုသာ စီမံနိုင်ပါသည်',
  Code: 'ကုဒ်',
  Phone: 'ဖုန်း',
  Manager: 'Manager',
  'Manager name': 'Manager အမည်',
  'Location / address': 'တည်နေရာ / လိပ်စာ',
  'Active Branch': 'Active Branch',
  Cancel: 'မလုပ်တော့ပါ',
  'Save Branch': 'Branch သိမ်းမည်',
  'Create, edit, suspend / safe active': 'ဖန်တီး၊ ပြင်၊ suspend / active ပြန်လုပ်နိုင်သည်',
  'No manager': 'Manager မသတ်မှတ်ရသေး',
  Edit: 'ပြင်မည်',
  Suspend: 'Suspend',
  'Safe Active': 'Active ပြန်ဖွင့်မည်',
  'Staff Role & Permission': 'Staff Role နှင့် Permission',
  'Last login': 'နောက်ဆုံးဝင်ရောက်ချိန်',
  'No login yet': 'မဝင်ရောက်ရသေးပါ',
  'All / Main Shop': 'အားလုံး / Main Shop',
  'No branch limit': 'Branch ကန့်သတ်ချက်မရှိ',
  'Staff Title': 'Staff ခေါင်းစဉ်',
  Role: 'Role',
  Reset: 'Reset',
  'Shop Activity Log': 'Shop လုပ်ဆောင်ချက် မှတ်တမ်း',
  'Branch / Staff changes under this shop': 'ဒီ shop အောက်က Branch / Staff အပြောင်းအလဲများ',
  'Password Reset': 'Password Reset',
  'Temporary Password': 'ယာယီ Password',
  'At least 8 characters': 'အနည်းဆုံး 8 လုံး',
  'Reset Password': 'Password Reset လုပ်မည်',
  REPAIR: 'REPAIR',
  'Import Existing Repair ID': 'ရှိပြီးသား Repair ID ကို Import လုပ်မည်',
  'Repair ID, customer, phone, device, IMEI or issue': 'Repair ID၊ customer၊ phone၊ device၊ IMEI သို့ issue',
  'All Statuses': 'Status အားလုံး',
  'All Sources': 'Source အားလုံး',
  'Mahar Shwe Import': 'Mahar Shwe Import',
  'Provider Import': 'Provider Import',
  'Partner Handoff': 'Partner Handoff',
  'Repair ID': 'Repair ID',
  Customer: 'Customer',
  Device: 'Device',
  Problem: 'ပြဿနာ',
  Source: 'Source',
  Status: 'Status',
  Received: 'လက်ခံထား',
  Amount: 'ပမာဏ',
  'No IMEI/Serial': 'IMEI/Serial မချိတ်ရသေး',
  'No repair jobs found.': 'Repair jobs မတွေ့ပါ',
  'Loading repairs...': 'Repair များ ဖွင့်နေပါသည်...',
  Showing: 'ပြသထားသည်',
  Previous: 'ယခင်',
  Next: 'နောက်',
  Page: 'စာမျက်နှာ',
  'Unique Device Repair History': 'တူညီသော Device Repair မှတ်တမ်း',
  'Hide History Search': 'History Search ဖျောက်မည်',
  'Open History Search': 'History Search ဖွင့်မည်',
  'IMEI or Serial Number': 'IMEI သို့ Serial Number',
  History: 'မှတ်တမ်း',
  'Repair Information': 'Repair အချက်အလက်',
  Condition: 'အခြေအနေ',
  Accessories: 'ပါဝင်ပစ္စည်းများ',
  Diagnosis: 'စစ်ဆေးချက်',
  Resolution: 'ဖြေရှင်းချက်',
  Technician: 'Technician',
  'Final Cost': 'နောက်ဆုံးကုန်ကျစရိတ်',
  'Warranty Until': 'Warranty သက်တမ်း',
  'Timeline Note': 'Timeline မှတ်စု',
  'Device Identity': 'Device Identity',
  'Device identity linked': 'Device identity ချိတ်ပြီးပါပြီ',
  'Repair Timeline': 'Repair Timeline',
  'No timeline events yet.': 'Timeline event မရှိသေးပါ',
  'Loading repair...': 'Repair detail ဖွင့်နေပါသည်...',
  'New Repair Intake': 'Repair လက်ခံမှုအသစ်',
  'Customer Name': 'Customer အမည်',
  'Device Brand': 'Device Brand',
  'Device Model': 'Device Model',
  'Estimated Cost': 'ခန့်မှန်းကုန်ကျစရိတ်',
  Deposit: 'စပေါ်ငွေ',
  'Optional Details ဖြည့်မည်': 'Optional အချက်အလက်များ ဖြည့်မည်',
  'Optional Details ဖျောက်မည်': 'Optional အချက်အလက်များ ဖျောက်မည်',
  Priority: 'ဦးစားပေး',
  'Intake Condition': 'လက်ခံချိန် အခြေအနေ',
  Notes: 'မှတ်စု',
  'Create Repair': 'Repair ဖန်တီးမည်',
  'Supplier Master': 'Supplier Master',
  'visible suppliers': 'မြင်ရသော supplier များ',
  'Active Suppliers': 'Active Supplier များ',
  'New Supplier': 'Supplier အသစ်',
  'Edit Supplier': 'Supplier ပြင်မည်',
  'Code can be generated automatically.': 'Code ကို အလိုအလျောက်ဖန်တီးနိုင်သည်',
  'Supplier Code': 'Supplier Code',
  'Supplier Name *': 'Supplier Name *',
  'Supplier / Company name': 'Supplier / Company name',
  'Create Supplier': 'Supplier ဖန်တီးမည်',
  'Save Changes': 'ပြောင်းလဲမှု သိမ်းမည်',
  'Open Purchase Orders': 'Purchase Orders ဖွင့်မည်',
  'Supplier updated.': 'Supplier ပြင်ပြီးပါပြီ',
  'Supplier disabled.': 'Supplier ကို ပိတ်ထားပါပြီ',
  'Supplier enabled.': 'Supplier ကို ပြန်ဖွင့်ပါပြီ',
  'Purchase → Stock Auto Add': 'Purchase → Stock Auto Add',
  'No purchase history yet': 'Purchase history မရှိသေးပါ',
  'Loading…': 'ဖွင့်နေပါသည်…',
  'Business Reports': 'လုပ်ငန်းအစီရင်ခံစာများ',
  'Live database': 'Live database',
  'Top Selling Products': 'ရောင်းအားအကောင်းဆုံး ပစ္စည်းများ',
  'View all': 'အားလုံးကြည့်မည်',
  'Payments & Accounts': 'ငွေပေးချေမှုနှင့် စာရင်း',
  'Reports': 'အစီရင်ခံစာများ',
  'Supplier Purchase': 'Supplier ဝယ်ယူမှု',
  'Supplier Purchase Report': 'ပစ္စည်းသွင်းသူ အဝယ်အစီရင်ခံစာ',
  'Goods received by supplier': 'Supplier အလိုက် လက်ခံထားသောပစ္စည်းများ',
  'Receipts': 'လက်ခံမှုများ',
  'Total Purchased': 'စုစုပေါင်းဝယ်ယူမှု',
  'Low Stock': 'Low Stock',
  'Cryptographic Audit Trail': 'လုံခြုံရေး Audit Trail',
  'Checking Audit Chain': 'Audit Chain စစ်ဆေးနေပါသည်',
  'Audit Chain Verified': 'Audit Chain မှန်ကန်ပါသည်',
  'Integrity Check Failed': 'Integrity Check မအောင်မြင်ပါ',
  'Search actor, action, target, request ID or IP': 'actor၊ action၊ target၊ request ID သို့ IP ရှာပါ',
  'No audit events found.': 'Audit event မတွေ့ပါ',
  'Loading audit events…': 'Audit event များ ဖွင့်နေပါသည်…',
  'events': 'events',
  'Audit request failed': 'Audit request မအောင်မြင်ပါ',
  'Audit chain verification failed': 'Audit chain verification မအောင်မြင်ပါ',
  'Audit chain verified:': 'Audit chain verified:',
  'Backup & Disaster Recovery': 'Backup နှင့် Disaster Recovery',
  'Backup system is healthy': 'Backup system ကောင်းမွန်နေသည်',
  'Backup system needs attention': 'Backup system ကို စစ်ဆေးရန်လိုသည်',
  'Latest Verified Archive': 'နောက်ဆုံး အတည်ပြုပြီး Archive',
  'Backup file details without exposing database credentials.': 'Database credential မဖော်ပြဘဲ backup file အချက်အလက်ကိုပြပါသည်',
  'Recovery Policy': 'Recovery Policy',
  'Production recovery controls and expected schedule.': 'Production recovery control နှင့် မျှော်မှန်းထားသော schedule',
  'Last Backup': 'နောက်ဆုံး Backup',
  'Tenant Backup Age': 'Tenant Backup Age',
  'hours since archive': 'archive လုပ်ပြီး နာရီကြာချိန်',
  'Backup status request failed': 'Backup status request မအောင်မြင်ပါ',
  'Password Reset is Admin only': 'Password Reset ကို Admin သာ လုပ်နိုင်သည်',
  'Admin Password Reset': 'Admin Password Reset',
  'ADMIN ONLY': 'ADMIN ONLY',
  'Reset ပြီးနောက် User ကို Temporary Password ပေးပြီး Login ပြန်ဝင်ခိုင်းပါ။': 'Reset ပြီးနောက် User ကို Temporary Password ပေးပြီး Login ပြန်ဝင်ခိုင်းပါ။',
  'password reset completed': 'password reset completed',
  'Copy Password': 'Password Copy',
  'Loading settings...': 'Settings ဖွင့်နေပါသည်...',
  'License Status': 'License အခြေအနေ',
  'Loading customer history…': 'Customer history ဖွင့်နေပါသည်…',
  'Source, category, note, account, staff…': 'source၊ category၊ note၊ account၊ staff ရှာပါ…',
  'Export CSV': 'CSV Export',
  'No records found for this date range.': 'ဒီရက်အပိုင်းအခြားအတွက် record မတွေ့ပါ',
  'Loading records…': 'Record များ ဖွင့်နေပါသည်…',
  'Loading stock data…': 'Stock data ဖွင့်နေပါသည်…',
  'No stock records found': 'Stock record မတွေ့ပါ',
  'Loading movement history…': 'Movement history ဖွင့်နေပါသည်…',
  'Loading products…': 'Product များ ဖွင့်နေပါသည်…',
  'No available products found': 'ရောင်းချနိုင်သော product မတွေ့ပါ',
  'products': 'products',
  'Loading tenant users...': 'Tenant user များ ဖွင့်နေပါသည်...',
  'No users found.': 'User မတွေ့ပါ',
  'Search name, username or role': 'name၊ username သို့ role ရှာပါ',
  'User': 'User',
  'Tenant': 'Tenant',
  'Last Login': 'နောက်ဆုံးဝင်ရောက်ချိန်',
  'Action': 'လုပ်ဆောင်ချက်',
  'Search code or supplier name': 'code သို့ supplier name ရှာပါ',
  'Loading suppliers…': 'Supplier များ ဖွင့်နေပါသည်…',
  'Supplier Returns': 'Supplier Return များ',
  'Received goods minus returns and payments': 'လက်ခံထားသောပစ္စည်းများမှ return နှင့် payment ကို နှုတ်ပြီး',
  'Outstanding': 'ပေးရန်ကျန်',
  'payments': 'payments',
  'Supplier master': 'Supplier master',
  'Progress': 'တိုးတက်မှု',
  'Returned': 'ပြန်ပို့ပြီး',
  'Paid': 'Paid',
  'Select supplier': 'Supplier ရွေးပါ',
  'PO': 'PO',
  'Net Received': 'Net Received',
  'Pay': 'ပေးချေမည်',
  'Supplier Payments': 'Supplier ငွေပေးချေမှုများ',
  'Supplier': 'Supplier',
  'Date': 'ရက်စွဲ',
  'Note': 'မှတ်စု',
  'Copy': 'Copy',
  'Find': 'ရှာမည်',
  'Delete': 'ဖျက်မည်',
  'Completed': 'ပြီးစီးပြီး',
  'Complete': 'ပြီးစီးအောင်လုပ်မည်',
  'Reopen': 'ပြန်ဖွင့်မည်',
  'Collected': 'ယူပြီး',
  'Not Collected': 'မယူရသေး',
  'Undo Pickup': 'Pickup ပြန်ဖြုတ်မည်',
  'Pending': 'စောင့်ဆိုင်းနေ',
  'Customer Portal · Notification · Pickup · Warranty': 'Customer Portal · Notification · Pickup · Warranty',
  'Customer-facing operation form': 'Customer ဘက်ဆိုင်ရာ operation form',
  'Customer Status Link': 'Customer Status Link',
  'Generate & Copy Link': 'Link ထုတ်ပြီး Copy',
  'Notification Targets': 'Notification Target များ',
  'Public status enabled': 'Public status ဖွင့်ထားသည်',
  'Save Notification Settings': 'Notification Setting သိမ်းမည်',
  'Secure Pickup': 'Secure Pickup',
  'Generate Pickup Code': 'Pickup Code ထုတ်မည်',
  '4-digit code': 'ဂဏန်း ၄ လုံး code',
  'Verify': 'အတည်ပြုမည်',
  'Warranty': 'Warranty',
  'Not configured': 'မသတ်မှတ်ရသေး',
  'Open Warranty Claim': 'Warranty Claim ဖွင့်မည်',
  'Notification Outbox': 'Notification Outbox',
  'Warranty Claims': 'Warranty Claim များ',
  'Pickup Security': 'Pickup လုံခြုံရေး',
  'Verified · ယူပြီး': 'အတည်ပြုပြီး · ယူပြီး',
  'MAHAR POS REPAIR TRACKING': 'MAHAR POS REPAIR TRACKING',
  'Repair Status': 'Repair Status',
  'Current / Temporary Password': 'လက်ရှိ / ယာယီ Password',
  'New Password': 'Password အသစ်',
  'Confirm Password': 'Password အတည်ပြု',
  'At least 6 characters': 'အနည်းဆုံး ၆ လုံး',
  'Enter the same password': 'Password တူအောင် ပြန်ထည့်ပါ',
  'Copying...': 'Copy လုပ်နေသည်...',
  'Delete User': 'User ဖျက်မည်',
  'Delete User Permanently': 'User ကို အပြီးဖျက်မည်',
  'Service Jobs': 'Service Job များ',
  'Search by date, month or ID': 'ရက်၊ လ သို့ ID ဖြင့်ရှာပါ',
  'ID / Customer / Device': 'ID / Customer / Device',
  'No service jobs found.': 'Service job မတွေ့ပါ',
  'Total Service Jobs': 'စုစုပေါင်း Service Job',
  'Pickup': 'Pickup',
  'Cost': 'ကုန်ကျစရိတ်',
  'Device / Problem': 'Device / ပြဿနာ',
  'Google Sheet Configure': 'Google Sheet Configure',
  'Google Sheet Web App URL': 'Google Sheet Web App URL',
  'Paste Google Apps Script Web App URL': 'Google Apps Script Web App URL ထည့်ပါ',
  'Repair Tracking Web App URL': 'Repair Tracking Web App URL',
  'Accounting Daily Web App URL': 'Accounting Daily Web App URL',
  'App Token / API Key': 'App Token / API Key',
  'Optional security token': 'Optional security token',
  'Save Configuration': 'Configuration သိမ်းမည်',
  'Voucher · Customer Portal · Export': 'Voucher · Customer Portal · Export',
  'Confirm & Complete Sale': 'Sale အတည်ပြုပြီး ပြီးစီးမည်',
  'Sale Completed': 'Sale ပြီးစီးပြီ',
  'Clear Split': 'Split ရှင်းမည်',
  'One or more split payment amounts are invalid.': 'Split Payment amount တစ်ခုမမှန်ပါ',
  'Split payment total is less than the sale total.': 'Split Payment စုစုပေါင်းသည် Sale Total ထက်နည်းနေသည်',
  'Complete Cash Payout': 'Cash ထုတ်ပေးမှု ပြီးစီးမည်',
  'Collect Remaining Payment': 'ကျန်ငွေ လက်ခံမည်',
  'Enable Notification': 'Notification ဖွင့်မည်',
  'Low stock browser notification enabled.': 'Low stock browser notification ဖွင့်ပြီးပါပြီ',
  'Notification status unavailable': 'Notification status မရနိုင်ပါ',
  'Notification worker was updated. Please refresh once, then press Update device again.': 'Notification worker update ဖြစ်ထားပါသည်။ Refresh တစ်ချက်လုပ်ပြီး Update device ပြန်နှိပ်ပါ။',
});
const ENGLISH = Object.fromEntries(Object.entries(MYANMAR).map(([en, my]) => [my, en]));
const textState = new WeakMap();
const elementState = new WeakMap();
const TRANSLATABLE_ATTRIBUTES = ['placeholder', 'title', 'aria-label', 'value'];

function normalizedLanguage(value) {
  return value === 'en' ? 'en' : 'my';
}

export function getProjectLanguage() {
  if (typeof document === 'undefined') return 'my';
  return normalizedLanguage(
    document.documentElement.dataset.language
    || document.documentElement.lang
    || window.localStorage?.getItem?.(STORAGE_KEY)
    || 'my',
  );
}

export function pickLanguageText(english, myanmar) {
  return getProjectLanguage() === 'en' ? english : myanmar;
}

function canonicalText(value) {
  const trimmed = value.trim();
  return ENGLISH[trimmed] ? value.replace(trimmed, ENGLISH[trimmed]) : value;
}

// Keep Myanmar mode readable without rewriting product names or other user data.
// These replacements run only after a string has matched the central UI dictionary.
const MYANMAR_UI_TERMS = [
  [/Project Settings/gi, 'စနစ်ဆက်တင်'],
  [/System Settings/gi, 'စနစ်ဆက်တင်'],
  [/Business Profile/gi, 'ဆိုင်အချက်အလက်'],
  [/Sales History/gi, 'အရောင်းမှတ်တမ်း'],
  [/Sale History/gi, 'အရောင်းမှတ်တမ်း'],
  [/Product Categories/gi, 'ပစ္စည်းအမျိုးအစားများ'],
  [/Product Category/gi, 'ပစ္စည်းအမျိုးအစား'],
  [/Product Name/gi, 'ပစ္စည်းအမည်'],
  [/Products API/gi, 'ပစ္စည်း API'],
  [/Products/gi, 'ပစ္စည်းများ'],
  [/Product/gi, 'ပစ္စည်း'],
  [/Customer Name/gi, 'ဖောက်သည်အမည်'],
  [/Customer Phone/gi, 'ဖောက်သည်ဖုန်း'],
  [/Customers/gi, 'ဖောက်သည်များ'],
  [/Customer/gi, 'ဖောက်သည်'],
  [/Users/gi, 'အသုံးပြုသူများ'],
  [/User/gi, 'အသုံးပြုသူ'],
  [/Display Name/gi, 'ပြသမည့်အမည်'],
  [/Opening Page/gi, 'စဖွင့်မည့်စာမျက်နှာ'],
  [/Page Size/gi, 'တစ်မျက်နှာပြသမည့်အရေအတွက်'],
  [/Table Density/gi, 'ဇယားအကွာအဝေး'],
  [/Sidebar/gi, 'ဘေးဘား'],
  [/Dashboard/gi, 'ဒက်ရှ်ဘုတ်'],
  [/Reports/gi, 'အစီရင်ခံစာများ'],
  [/Report/gi, 'အစီရင်ခံစာ'],
  [/Settings/gi, 'ဆက်တင်'],
  [/Preference/gi, 'ကိုယ်ပိုင်ရွေးချယ်မှု'],
  [/Slip/gi, 'ဘောင်ချာ'],
  [/Voucher/gi, 'ဘောင်ချာ'],
  [/Invoice/gi, 'ပြေစာ'],
  [/Payment/gi, 'ငွေပေးချေမှု'],
  [/Cashier/gi, 'ငွေကိုင်'],
  [/Wallet/gi, 'ငွေအိတ်'],
  [/Account/gi, 'ငွေစာရင်း'],
  [/Stock/gi, 'လက်ကျန်'],
  [/Variant/gi, 'အမျိုးအစားခွဲ'],
  [/Category/gi, 'အမျိုးအစား'],
  [/Search/gi, 'ရှာဖွေ'],
  [/Filter/gi, 'စစ်ထုတ်မှု'],
  [/Save/gi, 'သိမ်းဆည်း'],
  [/Edit/gi, 'ပြင်ဆင်'],
  [/Delete/gi, 'ဖျက်'],
  [/Deactivate/gi, 'ပိတ်ထား'],
  [/Export/gi, 'ထုတ်ယူ'],
  [/Reprint/gi, 'ပြန်လည်ပရင့်ထုတ်'],
  [/Print/gi, 'ပရင့်ထုတ်'],
  [/Detail/gi, 'အသေးစိတ်'],
  [/Confirm/gi, 'အတည်ပြု'],
  [/Step/gi, 'အဆင့်'],
  [/Theme/gi, 'အပြင်အဆင်'],
  [/Language/gi, 'ဘာသာစကား'],
  [/Phone Shop/gi, 'ဖုန်းဆိုင်'],
  [/Repair/gi, 'ပြင်ဆင်မှု'],
  [/Supplier/gi, 'ပစ္စည်းသွင်းသူ'],
  [/Purchase/gi, 'အဝယ်'],
  [/Income/gi, 'ဝင်ငွေ'],
  [/Expense/gi, 'ထွက်ငွေ'],
  [/Profit/gi, 'အမြတ်'],
  [/Cost/gi, 'အရင်း'],
  [/Price/gi, 'ဈေးနှုန်း'],
  [/Amount/gi, 'ပမာဏ'],
  [/Status/gi, 'အခြေအနေ'],
  [/Note/gi, 'မှတ်ချက်'],
  [/Login/gi, 'အကောင့်ဝင်'],
];

function normalizeMyanmarUiText(value) {
  return MYANMAR_UI_TERMS.reduce(
    (result, [pattern, replacement]) => result.replace(pattern, replacement),
    value,
  );
}

function translatedText(value, language) {
  if (language === 'en') return value;
  const trimmed = value.trim();
  return MYANMAR[trimmed]
    ? value.replace(trimmed, normalizeMyanmarUiText(MYANMAR[trimmed]))
    : value;
}

function shouldTranslateAttribute(element, name) {
  if (!element?.getAttribute) return false;
  if (name === 'value') {
    return ['BUTTON', 'INPUT'].includes(element.tagName)
      && ['button', 'submit', 'reset'].includes((element.getAttribute('type') || 'button').toLowerCase());
  }
  return element.hasAttribute(name);
}

function translateAttribute(element, name, language) {
  if (!shouldTranslateAttribute(element, name)) return;
  const current = element.getAttribute(name) || '';
  if (!current.trim()) return;
  const previous = elementState.get(element) || {};
  const canonical = previous[name] && current === previous[`${name}Applied`]
    ? previous[name]
    : canonicalText(current);
  const next = translatedText(canonical, language);
  elementState.set(element, { ...previous, [name]: canonical, [`${name}Applied`]: next });
  if (current !== next) element.setAttribute(name, next);
}

function translateElement(element, language) {
  if (!element || element.nodeType !== Node.ELEMENT_NODE) return;
  if (element.closest?.('[data-i18n-ignore="true"]')) return;
  TRANSLATABLE_ATTRIBUTES.forEach((name) => translateAttribute(element, name, language));
 }

function translateNode(node, language) {
  if (!node || node.nodeType !== Node.TEXT_NODE) return;
  const parent = node.parentElement;
  if (!parent || ['SCRIPT', 'STYLE', 'TEXTAREA', 'INPUT', 'CODE', 'PRE'].includes(parent.tagName)) return;
  if (parent.closest?.('[data-i18n-ignore="true"]')) return;
  const current = node.nodeValue || '';
  if (/^\s*PHASE\s*\d+/i.test(current.trim())) {
    node.nodeValue = '';
    return;
  }
  if (!current.trim()) return;

  const previous = textState.get(node);
  const canonical = previous && current === previous.lastApplied
    ? previous.canonical
    : canonicalText(current);
  const next = translatedText(canonical, language);
  textState.set(node, { canonical, lastApplied: next });
  if (current !== next) node.nodeValue = next;
}

function translateTree(root, language) {
  if (!root || typeof document === 'undefined') return;
  if (root.nodeType === Node.TEXT_NODE) {
    translateNode(root, language);
    return;
  }
  if (root.nodeType !== Node.ELEMENT_NODE && root !== document.body) return;
  translateElement(root, language);
  if (root.querySelectorAll) {
    root.querySelectorAll('*').forEach((element) => translateElement(element, language));
  }
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    translateNode(node, language);
    node = walker.nextNode();
  }
}

export function applyProjectLanguage(language) {
  if (typeof document === 'undefined') return;
  const selected = normalizedLanguage(language);
  document.documentElement.lang = selected;
  document.documentElement.dataset.language = selected;
  try {
    window.localStorage.setItem(STORAGE_KEY, selected);
  } catch {
    // Storage can be unavailable in privacy mode.
  }
  translateTree(document.body, selected);
  window.dispatchEvent(new CustomEvent('mahar-project-language', { detail: selected }));
}

export default function ProjectLanguageRuntime({ children }) {
  useEffect(() => {
    let language = normalizedLanguage(
      window.localStorage.getItem(STORAGE_KEY)
      || document.documentElement.dataset.language
      || 'my',
    );
    applyProjectLanguage(language);

    const observer = new MutationObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.type === 'characterData') translateNode(entry.target, language);
        entry.addedNodes.forEach((node) => translateTree(node, language));
      });
    });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });

    const handleLanguage = (event) => {
      language = normalizedLanguage(event.detail);
      translateTree(document.body, language);
    };
    window.addEventListener('mahar-project-language', handleLanguage);

    return () => {
      observer.disconnect();
      window.removeEventListener('mahar-project-language', handleLanguage);
    };
  }, []);

  return children;
}
