import React from 'react';
import { ChevronRight, Handshake, Loader2 } from 'lucide-react';

const money = (v) => `${Number(v || 0).toLocaleString('en-US')} ကျပ်`;
const dateText = (v) => v ? new Date(v).toLocaleDateString('en-GB') : '—';
const badge = (v) => `psw-status psw-${String(v || '').toLowerCase().replaceAll('_', '-')}`;
const Empty = ({ title, text }) => <div className="psw-empty"><Handshake/><b>{title}</b><span>{text}</span></div>;

export default function PartnerSettlementTables({ tab, settlements, ledger, partners, busy, onOpen, onMarkPaid }) {
  if (tab === 'partners') return <div className="psw-partner-grid">{partners.length ? partners.map((p) => <article className="psw-card psw-partner" key={p.id}><div className="psw-partner-logo">{p.partnerCode}</div><div><h3>{p.displayName}</h3><p>{p.providerName} → {p.partnerName}</p><span>{p.accessMode} · Customer pays {p.customerPaysPartner ? 'Partner' : 'Provider'}</span></div></article>) : <Empty title="Partner shop မရှိသေးပါ" text="Provider admin က partner tenant ကို link လုပ်ပါ။"/>}</div>;

  if (tab === 'ledger') return <div className="psw-card psw-table-card">{ledger.length ? <div className="psw-table-wrap"><table className="psw-table"><thead><tr><th>Partner Repair</th><th>Provider Repair</th><th>Partner</th><th>Customer Charge</th><th>Provider Due</th><th>Partner Profit</th><th>Settlement Status</th><th>Settlement</th></tr></thead><tbody>{ledger.map((x) => <tr key={x.id}><td><b>{x.partnerRepairNumber || '—'}</b></td><td><b>{x.providerRepairNumber || '—'}</b><small>{dateText(x.completedAt)}</small></td><td>{x.partnerName}<small>{x.partnerCode}</small></td><td>{money(x.customerCharge)}</td><td><strong>{money(x.providerDue)}</strong></td><td className="psw-success-text">{money(x.partnerProfit)}</td><td>{x.settlementId ? (x.customerPaid ? 'မရှင်းရသေး / Included' : 'Hold') : <button className={`psw-mini-button ${x.customerPaid ? 'success' : ''}`} onClick={() => onMarkPaid(x)} disabled={busy === `paid:${x.id}`}>{busy === `paid:${x.id}` ? <Loader2 className="psw-spin" size={14}/> : x.customerPaid ? 'မရှင်းရသေး ✓' : 'Mark Due'}</button>}</td><td><span className={badge(x.settlementStatus)}>{x.settlementStatus}</span></td></tr>)}</tbody></table></div> : <Empty title="Repair ledger မရှိသေးပါ" text="Completed + picked-up partner repairs ကို Sync Completed နှိပ်ပါ။"/>}</div>;

  return <div className="psw-card psw-table-card">{settlements.length ? <div className="psw-table-wrap"><table className="psw-table"><thead><tr><th>Settlement</th><th>Partner</th><th>Period</th><th>Jobs</th><th>Provider Due</th><th>Paid</th><th>Outstanding</th><th>Status</th><th/></tr></thead><tbody>{settlements.map((x) => <tr key={x.id}><td><b>{x.settlementNumber}</b><small>{dateText(x.createdAt)}</small></td><td><b>{x.partnerName}</b><small>{x.partnerCode} · {x.accessMode}</small></td><td>{dateText(x.periodStart)}<small>to {dateText(x.periodEnd)}</small></td><td>{x.totalJobs}</td><td><strong>{money(x.providerDue)}</strong></td><td>{money(x.paidAmount)}</td><td className={Number(x.outstandingAmount) ? 'psw-danger-text' : 'psw-success-text'}><strong>{money(x.outstandingAmount)}</strong></td><td><span className={badge(x.status)}>{x.status}</span></td><td><button className="psw-row-action" onClick={() => onOpen(x.id)}>{busy === `detail:${x.id}` ? <Loader2 className="psw-spin" size={17}/> : <ChevronRight size={18}/>}</button></td></tr>)}</tbody></table></div> : <Empty title="Settlement မရှိသေးပါ" text="Paid repair ledger ကို weekly settlement အဖြစ် Generate လုပ်ပါ။"/>}</div>;
}
